### ISSUE TITLE
Unable to find input class NumericRangeInput

### ISSUE THREAD

**Issue by jbermudes** [inossidabile/mastering_aa#4]
In Rails 4.2.5 with AA 1.0.pre2, AA can't load the class `NumericRangeInput`. This is probably because when the example says to use `filter :id, as: :numeric_range`, the newer versions of AA try to load the class named `NumericRangeInput`. 

Changing the class name to just `NumericRangeInput` seems to fix the issue.

See: http://stackoverflow.com/questions/34455537/adding-numeric-range-filtering-to-activeadmin/34567297?noredirect=1#comment56902165_34567297

**Comment by inossidabile** [comment]
This repo is a sample code for 2-years old article. It's a good thing you still can make use of it (what a shame for AA tho) but I'm not going to keep code updated. Thanks.
